### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by wa5ve** [little-fort/booster-bot#75]
I am a player using this robot, thank you for your contribution, the robot can not continue after running a game, or can not start to enter the game after opening, please ask you to update
![2024-11-14_170015](https://github.com/user-attachments/assets/ed230c6b-808a-428a-886c-1f925d088fec)
![2024-11-14_170032](https://github.com/user-attachments/assets/0f7785fc-daa0-4c30-bc69-ed572f660560)
![2024-11-14_170046](https://github.com/user-attachments/assets/edc77a9c-2d48-40d2-8918-5b7b530e591e)

**Comment by A1C4-R** [comment]
ah... Here you are

**Comment by little-fort** [comment]
Hi, I've published a new release: https://github.com/little-fort/booster-bot/releases/tag/v1.5.1

Give it another try with the latest version and let me know if it keeps failing for you

**Comment by wa5ve** [comment]
Hello, after I used the new version, I found a new problem. The robot always fails to click the main menu, that is, the button in the middle below. When the robot puts the mouse on the main, the main will not light up and will not be clicked, resulting in the inability to proceed to the next step.

**Comment by wa5ve** [comment]
> 嗨，我发布了一个新版本：https://github.com/little-fort/booster-bot/releases/tag/v1.5.1
> 
> 使用最新版本再试一次，如果它一直对您失败，请告诉我

Hello, thanks to your update，after I used the new version, I found a new problem. The robot always fails to click the main menu, that is, the button in the middle below. When the robot puts the mouse on the main, the main will not light up and will not be clicked, resulting in the inability to proceed to the next step.

**Comment by little-fort** [comment]
Thank you for catching that! Here is an updated release: https://github.com/little-fort/booster-bot/releases/tag/v1.5.2

Please try the latest version and let me know if you experience any more issues

**Comment by ruoruolxy** [comment]
> 感谢您发现这一点！以下是更新版本： https: [//github.com/little-fort/booster-bot/releases/tag/v1.5.2](https://github.com/little-fort/booster-bot/releases/tag/v1.5.2)
> 
> 请尝试最新版本，如果遇到任何问题请告知我

When running the robot in Conquest Mode, it will stop running at 3:00 and 11:00. (It may also be the case at 19:00, but it has not been verified. In addition, I don't speak English, so I translated this feedback through Google Translate. Thank you)

**Comment by little-fort** [comment]
> When running the robot in Conquest Mode, it will stop running at 3:00 and 11:00. (It may also be the case at 19:00, but it has not been verified. In addition, I don't speak English, so I translated this feedback through Google Translate. Thank you)

Can you explain more about what you mean when you say it will "stop running"? Providing a log file would also be helpful

**Comment by ruoruolxy** [comment]
> > 征服模式运行机器人时，会在3点和11点停止运行。（19点也可能如此，但未验证。另外我不会说英文，所以通过谷歌翻译翻译了这条反馈。谢谢）
> 
> 您能否进一步解释一下“停止运行”是什么意思？提供日志文件也会有所帮助
After I finish a Conquest game, the Enter button disappears when the mission is refreshed at 3:00/11:00 (UTC+8)
![20241120031414](https://github.com/user-attachments/assets/79b855a6-f71f-4618-a27c-582fe87b06a9)
![20241120031108](https://github.com/user-attachments/assets/bae0538b-d16a-4c56-802c-4847e3de95da)
![20241120031144](https://github.com/user-attachments/assets/5c38c3de-8691-46e4-9d1a-8fd2bdd251f3)

**Comment by little-fort** [comment]
Okay yes that is definitely a bug with the game client. The UI is known to have issues like this, often coinciding with the server refresh every 8 hours. This may also be region specific as I am unable to replicate it locally. 

Is the bot able to resume activity after you see the "Attempting blind reset clicks..." message?

**Comment by ruoruolxy** [comment]
> Okay yes that is definitely a bug with the game client. The UI is known to have issues like this, often coinciding with the server refresh every 8 hours. This may also be region specific as I am unable to replicate it locally.
> 
> Is the bot able to resume activity after you see the "Attempting blind reset clicks..." message?

The robot will not resume activity. The solution is to click the home button again and the enter button will appear. It seems that this problem occurs in Asia.

**Comment by little-fort** [comment]
Can you replicate this error again and send me the complete log file? The files are stored in the `logs` directory of the BoosterBot folder. I think I can add a workaround for this issue but I need a better understanding of the exact sequence the program is getting stuck on

**Comment by ruoruolxy** [comment]
> Can you replicate this error again and send me the complete log file? The files are stored in the `logs` directory of the BoosterBot folder. I think I can add a workaround for this issue but I need a better understanding of the exact sequence the program is getting stuck on

sure!Thank you so much!
[conquest-log-20241119091345.txt](https://github.com/user-attachments/files/17870919/conquest-log-20241119091345.txt)
[conquest-log-20241120024431.txt](https://github.com/user-attachments/files/17870922/conquest-log-20241120024431.txt)

**Comment by ruoruolxy** [comment]
> Can you replicate this error again and send me the complete log file? The files are stored in the `logs` directory of the BoosterBot folder. I think I can add a workaround for this issue but I need a better understanding of the exact sequence the program is getting stuck on

The latest log at 3:00(UTC+8) on the 23rd
[conquest-log-20241123025547.txt](https://github.com/user-attachments/files/17875263/conquest-log-20241123025547.txt)

**Comment by little-fort** [comment]
Perfect, thank you. I have a fix ready for this that I will be including in the next release

**Comment by little-fort** [comment]
Hi @ruoruolxy, I have published a new version that includes the fix for the "disappearing button" issue:

https://github.com/little-fort/booster-bot/releases/tag/v1.6.0

**Comment by wa5ve** [comment]
@little-fort Hello, thank you very much for your update. When running the script of version 1.6.0, I had such a problem: the robot would not enter the conquest mode, but would only keep selecting the home page and alliance page after starting, keep clicking to switch, and then exit. The log file is as follows:
![image](https://github.com/user-attachments/assets/222a5582-800c-4af7-ad28-52c6dc71c2c3)

> Hi @ruoruolxy, I have published a new version that includes the fix for the "disappearing button" issue:
> 
> https://github.com/little-fort/booster-bot/releases/tag/v1.6.0

**Comment by little-fort** [comment]
Hi, this is because of the active Deadpool's Diner event. You can start the program with the `-e` or `--event` parameter and it will adjust the menu navigation to account for the event button. Alternatively, you can set the `eventModeActive` option to true in the `appsettings.json` file to do this as well

**Comment by wa5ve** [comment]
> 嗨，这是因为活跃的 Deadpool's Diner 活动。您可以使用 or 参数启动程序，它将调整菜单导航以考虑事件按钮。或者，您也可以在文件中将选项设置为 true 来执行此操作`-e``--event``eventModeActive``appsettings.json`

Hello, thank you for your reply, I still can't run according to the Settings you said, no matter running Conquer, rank, Deadpool Restaurant, bot will switch back and forth between alliance and homepage and exit, see the video for details
https://youtube.com/shorts/_1ZRGiswqDo?feature=shared

**Comment by little-fort** [comment]
Okay, now I see what you mean. Can you try using the Repair Mode function? Start the app from the command line like so: `BoosterBot.exe --repair`

You should then see the program start with a screen that says "Repair Mode". Go through all the steps to fix the UI detection and let me know if it can recognize the main menu after that

**Comment by wa5ve** [comment]
Thank you for your reply. Hello, I performed repair operation, but every time I went here, there would be a serious error in the figure. I tried to download the file again, but it still failed.
![image](https://github.com/user-attachments/assets/6f0fefc8-f85f-4935-9e28-6c789414ff39)

**Comment by little-fort** [comment]
Interesting, I will have to investigate that later... Until then, try using the "Skip" option on that step and continuing through the rest of the process

**Comment by wa5ve** [comment]
Hello, thank you for your reply, in the fourth step can not skip, he will show the error and "press any key to push out", I input skip command is not working.

> 有趣的是，我稍后必须调查一下......在此之前，请尝试在该步骤中使用“跳过”选项并继续完成其余过程

**Comment by little-fort** [comment]
Hi, I have published a new release with various fixes and adjustments, please try using it and let me know if you find more issues:

https://github.com/little-fort/booster-bot/releases/tag/v1.6.1

**Comment by wa5ve** [comment]
> 您好，我发布了一个新版本，其中包含各种修复和调整，请尝试使用它，如果您发现更多问题，请告诉我：
> 
> https://github.com/little-fort/booster-bot/releases/tag/v1.6.1

Hello, thank you for your reply. After Deadpool Restaurant, I tried to use the bot to conquer mode, but the bot was switching back and forth between the homepage and the alliance again, but it could not enter the conquer mode, which was still the case after I tried to fix it. Thank you for your efforts, thank you

**Comment by little-fort** [comment]
> Hello, thank you for your reply. After Deadpool Restaurant, I tried to use the bot to conquer mode, but the bot was switching back and forth between the homepage and the alliance again, but it could not enter the conquer mode, which was still the case after I tried to fix it. Thank you for your efforts, thank you

Hi, can you confirm that `eventModeActive` is now set to `false` in the `appsettings.json` file?

**Comment by wa5ve** [comment]
> > 您好，感谢您的回复。死侍餐厅之后，我尝试使用机器人征服模式，但机器人又在首页和联盟之间来回切换，但无法进入征服模式，在我尝试修复后仍然如此。感谢你们的努力，谢谢你们
> 
> 嗨，您能否确认现在已在文件中设置为 ？`eventModeActive``false``appsettings.json`

Hello, thank you for your reply. Deadpool Restaurant can run for a period of time, but since yesterday, it has repeatedly switched between the alliance and the home page. I have tried to repair and modify the Settings you mentioned, and found that no actual effect has been produced

**Comment by wa5ve** [comment]
Hello, thank you for your reply. I tried to download the bot again, and the following situation occurred, which still existed after I repaired it.
![4034107ac7d1cd42e6c948f76d29cb16](https://github.com/user-attachments/assets/fd08ea59-44d9-441e-a496-7fdaf6823e90)

**Comment by xyznsw** [comment]
> I am a player using this robot, thank you for your contribution, the robot can not continue after running a game, or can not start to enter the game after opening, please ask you to update ![2024-11-14_170015](https://private-user-images.githubusercontent.com/188437797/386118344-ed230c6b-808a-428a-886c-1f925d088fec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2OTYxMTMsIm5iZiI6MTczNTY5NTgxMywicGF0aCI6Ii8xODg0Mzc3OTcvMzg2MTE4MzQ0LWVkMjMwYzZiLTgwOGEtNDI4YS04ODZjLTFmOTI1ZDA4OGZlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMVQwMTQzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNWU1YTU2NGQzMjZkNmY2NjJlZTBmNGEwZjk0MmIxN2YxZjFmZjE4YWY4ZjVkOTViOGYzNWZiNzhiZjE5ODQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JYFVY5n_i9xSTmNYkWnhLBZTBU5LnPyKltrN-ml8f-4) ![2024-11-14_170032](https://private-user-images.githubusercontent.com/188437797/386118354-0f7785fc-daa0-4c30-bc69-ed572f660560.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2OTYxMTMsIm5iZiI6MTczNTY5NTgxMywicGF0aCI6Ii8xODg0Mzc3OTcvMzg2MTE4MzU0LTBmNzc4NWZjLWRhYTAtNGMzMC1iYzY5LWVkNTcyZjY2MDU2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMVQwMTQzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmE3OTU4NTk2NjVhM2JkZDNhZGI1ODE5MDMwMTFhNjczYmNjOGYwM2FlMjRmOWMyMGI2NWQ4NzgzMmE3MTUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CJ-_N4mOq1HH5-BF2H58S7m2PVCcLBOeby29oYICKMA) ![2024-11-14_170046](https://private-user-images.githubusercontent.com/188437797/386118358-edc77a9c-2d48-40d2-8918-5b7b530e591e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2OTYxMTMsIm5iZiI6MTczNTY5NTgxMywicGF0aCI6Ii8xODg0Mzc3OTcvMzg2MTE4MzU4LWVkYzc3YTljLTJkNDgtNDBkMi04OTE4LTViN2I1MzBlNTkxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMVQwMTQzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTc1NTkwODRmOWQ5ZDk2Y2MzMzNjZTZhNDQxNmIzNDg3YzMwMDcxMzlhYzNlZjVlNTBiZmFhZDZjYjk3NzllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6v-3kHIexiBhIe1QaKuiQaslYQHdcDA4_QrvDBh3RqA)

I have exactly the same problem

**Comment by little-fort** [comment]
Moving to close this thread as it is quite stale and there have been a couple releases since the last post. If anyone in this thread is still interested, please try the latest release:

https://github.com/little-fort/booster-bot/releases/tag/v1.7.0

If you are still seeing issues, feel free to make a new thread and we can investigate further.
